############################################################
# +------------------------------------------------------+ #
# |                    EffectBlood                       | #
# +------------------------------------------------------+ #
############################################################
block: REDSTONE_WIRE
messages:
  error-block: 'Le bloc n''est pas bon. Merci de le changer.'


############################################################
# +------------------------------------------------------+ #
# |                       CoinFlip                       | #
# +------------------------------------------------------+ #
############################################################
# The min bet amount
minAmount: 1000

SkinRestorer-enable: true

GUI:
  Auto-Refill:
    active: true
    data: 15
    display_name: '&0'
  Size: 9
  Title: "&lPile ou Face"
  SkullItem:
    name: "&f&l%name%"
    lore:
      - ""
      - "&b&lMontant"
      - " &7$%money%"
      - ""
      - "&b&lCoté choisis"
      - " &7%side%"
      - ""
      - "&7Clique içi pour &a&lENTRER &7dans le pari !"
  BookInfo:
    type: BOOK
    name: "&b&lAide CoinFlip"
    lore:
      - ""
      - "&f/coinflip"
      - "&7Gui"
      - ""
      - "&f/coinflip <amount> <pile/face>"
      - "&7Démarrer un match"
      - ""
      - "&f/coinflip cancel"
      - "&7Annulé le match"
      - ""
      - "&f/coinflip toggle"
      - "&7Activer le broadcast"
  RefreshItem:
    type: CHEST
    name: "&b&lRefresh"
    lore:
      - "&7Clique içi pour rafraichir la liste"

AnimationGUI:
  Title: "&lLe gagnant est ..."

# messages
Messages:
  WinBroadcast: "&a%winner% &7a vaincu &c%loser% &7avec un montant de &7&n$%amount%&r"
  Entered: "&b&l[!] &bVous avez crée un pari avec un montant de &3$%amount% (&b/coinflip&3)"
  Canceled: "&e&l[!] &eVous vous êtes retiré du match!"
  CanceledHelp: "&e&l[!] &ePour annulé un match tape &6/cf cancel"
  ReceivedMoney: " &a&l+ %amount% +"
  LostMoney: " &c&l- %amount% -"
  NotEnoughMoney: "&c&l[!] &cTu n'a pas assez de monnaie pour entrer dans le pari!"
  NotEnoughEnterMoney: "&c&l[!] &cLe montant du pari doit être supérieur ou égale à &4$1,000!"
  AlreadyInBet: "&c&l[!] &cVous êtes dèjà dans un pari!"
  NotInBet: "&e&l[!] &eVous n'êtes pas membre d'un pari!"
  ToggleON: "&e&l[!] &eCoinFlip broadcasts are &a&lON"
  ToggleOFF: "&e&l[!] &eCoinFlip broadcasts are &c&lOFF"


############################################################
# +------------------------------------------------------+ #
# |                        Trade                         | #
# +------------------------------------------------------+ #
############################################################
Allow-Distance:
  enable: true
  radius: 10

Allow-inter-world:
  enable: true
