############################################################
# +------------------------------------------------------+ #
# |                    EffectBlood                       | #
# +------------------------------------------------------+ #
############################################################
block: REDSTONE_WIRE
messages:
  error-block: 'Le bloc n''est pas bon. Merci de le changer.'




############################################################
# +------------------------------------------------------+ #
# |                       CoinFlip                       | #
# +------------------------------------------------------+ #
############################################################
# The min bet amount
minAmount: 1000

SkinRestorer-enable: true

GUI:
  Auto-Refill:
    active: true
    data: 15
    display_name: '&0'
  Size: 9
  Title: "&lCOIN FLIP"
  SkullItem:
    name: "&f&l%name%"
    lore:
      - ""
      - "&b&lWager"
      - " &7$%money%"
      - ""
      - "&b&lSide Chosen"
      - " &7%side%"
      - ""
      - "&7Click here to &a&lENTER &7the bet!"
  BookInfo:
    type: BOOK
    name: "&b&lCoin Flip Help"
    lore:
      - ""
      - "&f/coinflip"
      - "&7View all active coinflip matches"
      - ""
      - "&f/coinflip <amount> <heads/tails>"
      - "&7Start a coinflip match"
      - ""
      - "&f/coinflip cancel"
      - "&7Remove your coinflip match"
      - ""
      - "&f/coinflip toggle"
      - "&7Toggles coinflip broadcasts"
  RefreshItem:
    type: CHEST
    name: "&b&lRefresh"
    lore:
      - "&7Click here to refresh this page"

AnimationGUI:
  Title: "&lWINNER IS.."

# messages
Messages:
  WinBroadcast: "&7&l** &a%winner% &7has defeated &c%loser% &7in a &7&n$%amount%&r &7/coinflip &7&l**"
  Entered: "&b&l[!] &bYou created a bet of &3$%amount% (&b/coinflip&3)"
  Canceled: "&e&l[!] &eYou removed yourself from the coinflip matches!"
  CanceledHelp: "&e&l[!] &eTo remove a coin flip type &6/cf cancel"
  ReceivedMoney: " &a&l+ %amount%"
  LostMoney: " &c&l- %amount%"
  NotEnoughMoney: "&c&l[!] &cYou dont have enough money to enter!"
  NotEnoughEnterMoney: "&c&l[!] &cAmount must be greater then &4$1,000!"
  AlreadyInBet: "&c&l[!] &cYou already are in the coins bet menu!"
  NotInBet: "&e&l[!] &eYou are not in the coinflip menu!"
  ToggleON: "&e&l[!] &eCoinFlip broadcasts are &a&lON"
  ToggleOFF: "&e&l[!] &eCoinFlip broadcasts are &c&lOFF"


############################################################
# +------------------------------------------------------+ #
# |                        Trade                         | #
# +------------------------------------------------------+ #
############################################################
Allow-Distance:
  enable: true
  radius: 10

Allow-inter-world:
  enable: true
