############################################################
# +------------------------------------------------------+ #
# |                 EffectBlood                          | #
# +------------------------------------------------------+ #
############################################################
block: REDSTONE_WIRE
messages:
  error-block: 'Le bloc n''est pas bon. Merci de le changer.'