name: Zekaria
version: 1.0.0
authors: [Neiyko,MrSuricate]
main: fr.mrsuricate.zekaria.Main
depends: [Vault]
softdepend: [SkinRestorer]
commands:
  alert:
    description: Broadcast custom
    permission: bc.use
  discord:
    description: Lien discord
  spawners:
    description: Achat spawner
  grades:
    description: Achat grade
  buykits:
    description: Achat de kit
  moderation:
    description: Interface de moderation
    permission: mod.interface.use
    aliases:
      - mod
  report:
    description: Commande de report
  coinflip:
    description: Ouvre le menu coinflip
    aliases: cf