name: Zekaria
version: 1.0.0
authors: [Neiyko,MrSuricate]
main: fr.mrsuricate.zekaria.Main
depends: [Vault, WordGuard, WorldEdit, MassiveCore, Factions]
softdepend: [SkinRestorer,HolographicDisplays]
commands:
  alert:
    description: Broadcast custom
    permission: bc.use
  CustomEnchant:
    description: Give CustomEnchant
    permission: ce.give
  discord:
    description: Lien discord
  ts:
    description: Lien ts
    aliases:
      - teamspeak
  site:
    description: Lien vers le site
  grades:
    description: Achat grade
  buykits:
    description: Achat de kit
  moderation:
    description: Interface de moderation
    permission: moderation.mod
    aliases:
      - mod
  report:
    description: Commande de report
  coinflip:
    description: Ouvre le menu coinflip
    aliases: cf
  trade:
    description: trade avec des joueurs
  giveall:
    description: Commande faite pour le giveall
    permission: giveall.use
    aliases:
      - ga
  clearchat:
    description: Commande clear chat
    permission: clearchat.use
    aliases:
      - cc
  chatlock:
    description: Commande lock chat
    permission: lockchat.use
    aliases:
      - cl
  staffchat:
    permission: staffchat.use
    aliases: sc
  enchere:
    description: Mettre des items au enchère
    permission: enchere.use
    aliases: auc
  warp:
    description: Api Warp
    aliases:
      - warp
      - wp
  localclear:
    description: Clear chat local
    aliases:
      - lc
  rules:
    description: Réglement du serveur
    aliases:
      - rule
  faction:
    description: Donne le top faction